helm install target/deploy/helm/eclipse-hono/ \
--namespace $k8s_namespace \
--name hono \
--set adapters.mqtt.svc.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=$resourcegroup_name \
--set adapters.http.svc.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=$resourcegroup_name \
--set adapters.amqp.svc.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=$resourcegroup_name \
--set deviceRegistryExample.svc.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-resource-group"=$resourcegroup_name \
--set deviceRegistryExample.storageClass=managed-premium-retain \
--set deviceRegistryExample.resetFiles=false \
--set adapters.mqtt.svc.loadBalancerIP=$mqtt_ip_address \
--set adapters.http.svc.loadBalancerIP=$http_ip_address \
--set adapters.amqp.svc.loadBalancerIP=$amqp_ip_address \
--set deviceRegistryExample.svc.loadBalancerIP=$registry_ip_address \
--set amqpMessagingNetworkExample.enabled=false \
--set adapters.amqpMessagingNetworkSpec.username=$service_bus_key_name \
--set adapters.amqpMessagingNetworkSpec.password=$service_bus_key \
--set adapters.amqpMessagingNetworkSpec.host=$service_bus_namespace.servicebus.windows.net \
--set adapters.amqpMessagingNetworkSpec.amqpHostname=$service_bus_namespace.servicebus.windows.net \
--set adapters.amqpMessagingNetworkSpec.idleTimeout=120000 \
--set adapters.amqpMessagingNetworkSpec.tlsEnabled=true \
--set adapters.commandAndControlSpec.username=$service_bus_key_name \
--set adapters.commandAndControlSpec.password=$service_bus_key \
--set adapters.commandAndControlSpec.host=$service_bus_namespace.servicebus.windows.net \
--set adapters.commandAndControlSpec.amqpHostname=$service_bus_namespace.servicebus.windows.net \
--set adapters.commandAndControlSpec.idleTimeout=120000 \
--set adapters.commandAndControlSpec.tlsEnabled=true
